name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master  # Или ваша основная ветка разработки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # Иначе, действие не сможет выполнить push

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # Или другой канал, который вы используете

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href=/TodoExampleApp/ --web-renderer html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build/web